# Generated by Django 5.2.6 on 2026-03-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Awaiting Approval'), ('solved', 'Fully Solved'), ('closed', 'Closed')], default='open', max_length=16),
        ),
    ]
