from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from typing import TYPE_CHECKING

from django.conf import settings
from django.db.models import Sum
from django.utils import timezone
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

if TYPE_CHECKING:
    from .models import PaymentConfirmation


def _ensure_invoice_dir() -> Path:
    root = Path(settings.MEDIA_ROOT) / "invoices"
    root.mkdir(parents=True, exist_ok=True)
    return root


def _build_invoice_pdf(payment_request, invoice_number: str, copy_label: str, target_path: Path) -> None:
    c = canvas.Canvas(str(target_path), pagesize=letter)
    width, height = letter

    # Header / Logo Area
    c.setFont("Helvetica-Bold", 24)
    c.setFillColorRGB(0.1, 0.1, 0.4) # Dark Blue
    c.drawString(50, height - 70, "INVOICE")
    
    c.setFont("Helvetica-Bold", 12)
    c.setFillColorRGB(0, 0, 0)
    c.drawRightString(width - 50, height - 70, "Property Management SaaS")
    
    # Invoice Info Header
    c.line(50, height - 85, width - 50, height - 85)
    
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 105, f"Invoice #: {invoice_number}")
    c.drawString(50, height - 120, f"Date: {timezone.now().date():%Y-%m-%d}")
    c.drawRightString(width - 50, height - 105, f"Type: {payment_request.get_payment_type_display().upper()}")
    c.drawRightString(width - 50, height - 120, f"Copy: {copy_label}")

    # Bill To / From
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, height - 160, "BILL FROM:")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 175, f"{payment_request.owner.full_name}")
    c.drawString(50, height - 190, f"Building: {payment_request.building.building_name} ({payment_request.building.building_code})")
    
    c.setFont("Helvetica-Bold", 11)
    c.drawRightString(width - 50, height - 160, "BILL TO:")
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 50, height - 175, f"{payment_request.tenant.full_name}")
    c.drawRightString(width - 50, height - 190, f"Apartment: {payment_request.apartment.apartment_name} ({payment_request.apartment.apartment_code})")

    # Description Table Header
    c.setFillColorRGB(0.95, 0.95, 0.95)
    c.rect(50, height - 240, width - 100, 25, fill=1, stroke=0)
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(60, height - 233, "DESCRIPTION")
    c.drawRightString(width - 60, height - 233, "AMOUNT")
    
    # Table Content
    c.setFont("Helvetica", 10)
    desc = f"{payment_request.get_payment_type_display()} - {payment_request.title}"
    c.drawString(60, height - 265, desc)
    c.drawRightString(width - 60, height - 265, f"${payment_request.amount:.2f}")
    
    c.setFont("Helvetica-Oblique", 9)
    period = f"Billing Period: {payment_request.billing_period_start} to {payment_request.billing_period_end}"
    c.drawString(60, height - 280, period)
    
    # Totals
    c.line(width - 200, height - 310, width - 50, height - 310)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(width - 200, height - 330, "TOTAL DUE")
    c.drawRightString(width - 60, height - 330, f"${payment_request.amount:.2f}")
    
    # Footer
    c.setFont("Helvetica", 8)
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.line(50, 50, width - 50, 50)
    c.drawCentredString(width / 2, 35, "Generated by Property Management System. Please contact your property manager for any queries.")
    
    c.showPage()
    c.save()


def generate_financial_statement(owner, start_date, end_date, target_path: Path) -> None:
    from .models import PaymentRequest, Expense
    c = canvas.Canvas(str(target_path), pagesize=letter)
    width, height = letter
    
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 60, "Property Financial Statement")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 80, f"Owner: {owner.full_name}")
    c.drawString(50, height - 95, f"Period: {start_date} to {end_date}")
    c.line(50, height - 105, width - 50, height - 105)

    # Fetch Data
    payments = PaymentRequest.objects.filter(owner=owner, status="approved", updated_at__date__range=[start_date, end_date])
    expenses = Expense.objects.filter(owner=owner, date__range=[start_date, end_date])
    
    revenue = payments.aggregate(Sum("amount"))["amount__sum"] or Decimal("0.00")
    costs = expenses.aggregate(Sum("amount"))["amount__sum"] or Decimal("0.00")
    
    # Summary Section
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 140, "Summary")
    c.setFont("Helvetica", 11)
    c.drawString(70, height - 165, f"Total Revenue (Approved):  ${revenue:.2f}")
    c.drawString(70, height - 185, f"Total Expenses:            -${costs:.2f}")
    c.setFont("Helvetica-Bold", 11)
    c.drawString(70, height - 210, f"NET PROFIT:                ${(revenue - costs):.2f}")
    
    # Table logic (simplified)
    y = height - 260
    c.drawString(50, y, "Recent Transactions")
    y -= 20
    c.setFont("Helvetica-Bold", 9)
    c.drawString(55, y, "DATE")
    c.drawString(120, y, "TITLE / ITEM")
    c.drawRightString(width - 60, y, "AMOUNT")
    c.line(50, y-5, width-50, y-5)
    
    c.setFont("Helvetica", 8)
    y -= 20
    for p in payments[:15]:
        c.drawString(55, y, f"{p.updated_at:%Y-%m-%d}")
        c.drawString(120, y, f"INCOME: {p.title} [{p.apartment.apartment_name}]")
        c.drawRightString(width-60, y, f"+{p.amount:.2f}")
        y -= 15
        if y < 100: break # Page break not handled here for simplicity in prototype
        
    for e in expenses[:15]:
        c.drawString(55, y, f"{e.date}")
        c.drawString(120, y, f"EXPENSE: {e.title} [{e.building.building_name}]")
        c.drawRightString(width-60, y, f"-{e.amount:.2f}")
        y -= 15
        if y < 100: break

    c.showPage()
    c.save()


def _next_invoice_number() -> str:
    date_part = timezone.now().strftime("%Y%m%d")
    today_prefix = f"INV-{date_part}-"
    from .models import Invoice

    latest = Invoice.objects.filter(invoice_number__startswith=today_prefix).order_by("invoice_number").last()
    if latest:
        try:
            last_seq = int(latest.invoice_number.rsplit("-", 1)[1])
        except (IndexError, ValueError):
            last_seq = 0
        next_seq = last_seq + 1
    else:
        next_seq = 1
    return f"INV-{date_part}-{next_seq:06d}"


def handle_payment_approval(confirmation: "PaymentConfirmation") -> "Invoice" | None:
    if confirmation.status != "approved" or hasattr(confirmation, "invoice"):
        return None
    payment_request = confirmation.payment_request
    invoice_number = _next_invoice_number()
    root = _ensure_invoice_dir()
    owner_path = root / f"{invoice_number}-owner.pdf"
    tenant_path = root / f"{invoice_number}-tenant.pdf"
    _build_invoice_pdf(payment_request, invoice_number, "Owner Copy", owner_path)
    _build_invoice_pdf(payment_request, invoice_number, "Tenant Copy", tenant_path)
    from .models import Invoice

    invoice = Invoice.objects.create(
        payment_request=payment_request,
        payment_confirmation=confirmation,
        invoice_number=invoice_number,
        invoice_date=timezone.now().date(),
        owner_copy_pdf=str(Path("invoices") / owner_path.name),
        tenant_copy_pdf=str(Path("invoices") / tenant_path.name),
        subtotal=payment_request.amount,
        total=payment_request.amount,
    )
    return invoice
