# Generated by Django 5.2.6 on 2026-03-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incompleteregistration',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incompleteregistration',
            name='otp_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='incompleteregistration',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
