# Generated by Django 5.2.6 on 2026-03-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentoccupancy',
            name='lease_document',
            field=models.FileField(blank=True, null=True, upload_to='leases/'),
        ),
    ]
